version: '3.5'

services:
  postgres:
    image: postgres:14
    command:
      - postgres
      - -c
      - max_connections=150
    environment:
      POSTGRES_USER: prefect
      POSTGRES_PASSWORD: test-password
      POSTGRES_DB: prefect_server
    healthcheck:
      interval: 10s
      retries: 60
      start_period: 2s
      test: pg_isready -q -d $${POSTGRES_DB} -U $${POSTGRES_USER} | grep "accepting connections" || exit 1
      timeout: 2s
    ports:
      - published: 5433
        target: 5432
    restart: on-failure
    volumes:
      - ./volumes/postgres:/var/lib/postgresql/data
    networks:
      - prefect
  minio:
    image: minio/minio
    environment:
      - MINIO_ROOT_USER=blablabla
      - MINIO_ROOT_PASSWORD=blablabla
    volumes:
      - ./volumes/minio:/data
    entrypoint: /bin/bash
    command: "-c 'mkdir -p /data/prefect-flows && sleep 10 && minio server /data --console-address :9001'"
    ports:
      - published: 9000
        target: 9000
      - published: 9001
        target: 9001
    networks:
      - prefect




  prefect-server:
    image: ${PREFECT_SERVER_IMAGE}
    command:
      - prefect
      - orion
      - start
    ports:
      - 4200:4200
    depends_on:
      - postgres
    volumes:
      - ${PWD}/volumes/prefect:/root/.prefect
      - ${PWD}/flows:/flows
    environment:
      PREFECT_ORION_API_HOST: 0.0.0.0
      PREFECT_ORION_DATABASE_CONNECTION_URL: postgresql+asyncpg://prefect:test-password@postgres:5432/prefect_server
      PREFECT_ORION_ANALYTICS_ENABLED: "false"
      PREFECT_LOGGING_SERVER_LEVEL: WARNING
      PREFECT_API_URL: http://prefect-server:4200/api
    networks:
      - prefect
  prefect-agent:
    image: ${PREFECT_AGENT_IMAGE}
    command:
      - prefect
      - agent
      - start
      - -q
      - default
    depends_on:
      - prefect-server
    environment:
      PREFECT_API_URL: http://prefect-server:4200/api
      PREFECT_LOGGING_LEVEL: DEBUG
      DOCKER_HOST: unix://var/run/docker.sock
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - prefect




  app:
    build:
      context: .
      dockerfile: app/app.Dockerfile
    command: python3 /usr/app/weather.py
    volumes:
      - ./app:/usr/app:ro
    environment:
      PREFECT_API_URL: "http://192.168.191.134:4200/api"
      MINIO_USE_SSL: ${MINIO_USE_SSL}
      MINIO_ACCESS_KEY: ${MINIO_ACCESS_KEY}
      MINIO_SECRET_KEY: ${MINIO_SECRET_KEY}
      MINIO_ENDPOINT: ${MINIO_ENDPOINT}
      MINIO_PREFECT_FLOWS_BUCKET_NAME: ${MINIO_PREFECT_FLOWS_BUCKET_NAME}
      MINIO_PREFECT_ARTIFACTS_BUCKET_NAME: ${MINIO_PREFECT_ARTIFACTS_BUCKET_NAME}
    depends_on:
      - minio
networks:
  prefect:
    name: prefect